apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  labels:
    app: nginx2
  annotations:
    configmap.reloader.stakater.com/reload: "nginx2-html"
spec:
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx2
          image: nginx:1.23.1
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html2
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
            requests:
              memory: '32Mi'
              cpu: '100m'
      volumes:
        - name: html2
          configMap:
            name: nginx2-html
