apiVersion: v1
kind: Service
metadata:
  name: nginx2
  labels:
    app: nginx2
  annotations:
    kots.io/when: '{{repl IsKurl }}'
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8082
  selector:
    app: nginx2
