apiVersion: v1
kind: Service
metadata:
  name: nginx1
  labels:
    app: nginx1
  annotations:
    kots.io/when: '{{repl IsKurl }}'
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8081
  selector:
    app: nginx1
