apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx2-html
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Multi Service App - nginx 2</title>
    </head>
    <body>
      <h2>Nginx Service 2</h2>
      repl{{ ConfigOption "multisvcapp-nginx2-text" }}
    </body>
    </html>
