apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: helmaliastest
spec:
  title: Helm subchart alias test app
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/black/kubernetes-icon-black.png
  allowRollback: false
