apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: echo-server
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: echo-server
    chartVersion: 0.5.23

  # helmVersion identifies the Helm Version used to render the Chart. Default is v2.
  helmVersion: v3

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    admin-console:
      enabled: false
    config:
      configOption: '{{repl ConfigOption "config_value" }}'

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder:
    admin-console:
      enabled: false
    replicated:
      config:
        configOption: '{{repl ConfigOption "config_value" }}'