apiVersion: v1
kind: Service
metadata:
  annotations:
  name: podinfo-web
  namespace: repl{{ ConfigOption "app_namespace" }}
spec:
  type: NodePort
  ports:
  - port: 9898
    protocol: TCP
    nodePort: 8082
  selector:
    app.kubernetes.io/name: ci-podinfo
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: podinfo-local
  namespace: repl{{ ConfigOption "app_namespace" }}
spec:
  type: NodePort
  ports:
  - port: 9898
    protocol: TCP
    nodePort: 9898
  selector:
    app.kubernetes.io/name: ci-podinfo
