apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: app-kafka
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: kafka
    chartVersion: "19.1.3"
    releaseName: app-kafka

  # helmVersion identifies the Helm Version used to render the chart. Default is v2.
  helmVersion: v3

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true

  # weight determines the order that charts with "useHelmInstall: true" are applied, with lower weights first.
  weight: 40

  namespace: default

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values: 
    replicas: 1
    deleteTopicEnable: true
    provisioning:
      enabled: true
      topics:
        - name: topic-test
          partitions: 1
          replicationFactor: 1
          ## https://kafka.apache.org/documentation/#topicconfigs
          config:
            max.message.bytes: 64000
            flush.messages: 1

