apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
   name: collectors
spec:
  collectors: 
    - clusterInfo: {}
    - clusterResources:
        namespaces:
        - default
    ###EXTERNAL POSTGRES###
    - postgres:
        collectorName: postgresql
        exclude: repl{{ ConfigOptionEquals "postgres_type" "embedded_postgres"}}
        uri: 'postgresql://{{repl ConfigOption "external_postgres_user"}}:{{repl ConfigOption "external_postgres_password"}}@{{repl ConfigOption "external_postgres_host"}}:{{repl ConfigOption "external_postgres_port"}}/{{repl ConfigOption "external_postgres_db"}}?sslmode={{repl ConfigOption "postgres_sslmode_value"}}'
  analyzers:
    - nodeResources:
        checkName: Check node memory resource
        outcomes:
          - warn: 
              when: "min(memoryCapacity) <= 8Gi"
              message: All nodes must have at least 8 GB of memory.
          - pass:
              message: Node has is at least 8 GB of memory.
    - storageClass:
        checkName: Required default storage classes
        storageClassName: "default"
        outcomes:
          - fail:
              message: The required storage class default was not found in the cluster.
          - pass:
              message: The required storage class default was found in the cluster.
    ###EXTERNAL POSTGRES###
    - postgres:
        checkName: Must be PostgreSQL 12.x or later
        collectorName: postgresql
        exclude: repl{{ ConfigOptionEquals "postgres_type" "embedded_postgres"}}
        outcomes:
          - fail:
              when: connected == false
              message: Cannot connect to PostgreSQL server
          - fail:
              when: version < 12.x
              message: The PostgreSQL server must be at least version 10
          - pass:
              message: The PostgreSQL server is ready
