apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  annotations:
    kots.io/when: '{{repl and (ConfigOptionEquals "postgres_type" "embedded_postgres") (eq (LicenseFieldValue "feature-flag-embedded-pg") "1") }}'
data:
  postgres-password: '{{repl ConfigOption "embedded_postgres_password" | Base64Encode }}'
  password: '{{repl ConfigOption "embedded_postgres_password" | Base64Encode }}'
  replication-password: '{{repl ConfigOption "embedded_postgres_password" | Base64Encode }}'
